### PR TITLE
[CI] Run Rector too

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@samsonasik Hey, I don't remember where exactly where it was, but the include-always change in `preload.php` breaks running Rector in our dev packages.

See the only broken job here: https://github.com/rectorphp/phpstan-rules/pull/12/checks?check_run_id=3755746585

Could you look at it?

**Comment by samsonasik** [comment]
This line seems need to be updated:

https://github.com/rectorphp/rector-src/blob/b7e7115bd99d6e5cef793d6e87a361b9fafc0597/bin/rector.php#L39

to check if the `vendor` exists:

```php
if (file_exists(__DIR__ . '/../preload.php') && is_dir(__DIR__ . '/../vendor)) {
```

**Comment by samsonasik** [comment]
I created PR https://github.com/rectorphp/rector-src/pull/934 for it.

**Comment by samsonasik** [comment]
Fixed, please re-run the build as I don't have access to this repository

**Comment by TomasVotruba** [comment]
Thank you :+1: 

I'm trying to re-run now

**Comment by TomasVotruba** [comment]
Good, it works :+1: Fail is expected, as some changes are made by Rector

**Pull request merged**
