### PR TITLE
Remove RequireRectorCategoryByGetNodeTypesRule from config

### PR DESCRIPTION
**Pull request by samsonasik**
Remove it from config to resolve e2e error at https://github.com/rectorphp/rector-src/actions/runs/4049597274/jobs/6966665432#step:8:10

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready, after merge, new tag i needed.

**Comment by TomasVotruba** [comment]
👍

**Comment by samsonasik** [comment]
@TomasVotruba could you create a tag for it? rector-src is using it as tagged version, I don't have write access to this repo

**Comment by TomasVotruba** [comment]
Done :+1:  0.6.5

**Pull request merged**
